/* ============================================================
   GEN-CHAIN — builds the daily "Chain" puzzles and writes them to
   src/data/generated/chain.js.

   Chain is a last-first word game: each word must start with the LAST letter of
   the previous word, every word common, no repeats. Build the longest chain you
   can from the day's seed word.

   BUILD-TIME emitter: we pick a daily SEED word and compute a PAR (a long valid
   chain a greedy solver finds from that seed) so the player has a target to chase.
   Validation of the player's OWN words happens in the browser against the shipped
   common-words set — the seed/par are all this file needs to ship.

   Run:  npm run gen:chain     (no network, no API key)
   ============================================================ */

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const WORDLIST_DIR = path.join(ROOT, "assets-src", "wordlists");
const OUT_DIR = path.join(ROOT, "src", "data", "generated");
const OUT_FILE = "chain.js";

const SEED = 2026;
const TARGET = 160; // rotation pool size
const MIN_LEN = 4; // seed / chain words are 4–8 letters (matches the runtime dict)
const MAX_LEN = 8;
const PAR_CAP = 8; // cap the target chain so par stays fun, not a grind

function mulberry32(a) {
  return function () {
    a |= 0;
    a = (a + 0x6d2b79f5) | 0;
    let t = Math.imul(a ^ (a >>> 15), 1 | a);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}
const rng = mulberry32(SEED);
const randInt = (n) => Math.floor(rng() * n);

// ── curated common words (4–8 letters), plus an index by first letter ─────────
function loadCommon() {
  const file = path.join(WORDLIST_DIR, "common-10k.txt");
  if (!fs.existsSync(file)) throw new Error("common-10k.txt not found in assets-src/wordlists.");
  const words = [];
  for (const raw of fs.readFileSync(file, "utf8").split(/\r?\n/)) {
    const w = raw.trim().toUpperCase();
    if (w.length >= MIN_LEN && w.length <= MAX_LEN && /^[A-Z]+$/.test(w)) words.push(w);
  }
  return words;
}
const WORDS = loadCommon();
const BY_FIRST = {};
for (const w of WORDS) (BY_FIRST[w[0]] ||= []).push(w);

// Greedy chain from `seed`: at each step jump to an unused word starting with the
// current last letter, preferring letters that have many continuations so the
// chain doesn't dead-end early. Deterministic-ish (seeded shuffles). Returns the
// chain; its length-1 is a defensible PAR (a human can usually get close).
function greedyChain(seed) {
  const used = new Set([seed]);
  let chain = [seed];
  let cur = seed;
  while (chain.length < PAR_CAP) {
    const letter = cur[cur.length - 1];
    const opts = (BY_FIRST[letter] || []).filter((w) => !used.has(w));
    if (!opts.length) break;
    // Pick a next word whose LAST letter still has SOME continuation (so we don't
    // strand the chain), but choose broadly among those for variety — deliberately
    // NOT always chasing the most-productive letter, which just funnels into the
    // S-plural cluster and makes every sample chain look identical.
    const viable = opts.filter((w) => (BY_FIRST[w[w.length - 1]]?.length || 0) > 0);
    const pool = viable.length ? viable : opts;
    const next = pool[randInt(pool.length)];
    used.add(next);
    chain.push(next);
    cur = next;
  }
  return chain;
}

console.log("\nGEN-CHAIN — building the daily Chain puzzles\n");
console.log(`  common pool: ${WORDS.length} words (${MIN_LEN}–${MAX_LEN} letters)`);

const puzzles = [];
const seenSeeds = new Set();
let guard = 0;
while (puzzles.length < TARGET && guard < TARGET * 40) {
  guard++;
  const seed = WORDS[randInt(WORDS.length)];
  if (seenSeeds.has(seed)) continue;
  // Skip seeds ending in S: they funnel straight into the S-plural super-cluster
  // (STATES→SPORTS→…), which makes every chain look the same. A varied seed keeps
  // the daily interesting.
  if (seed.endsWith("S")) continue;
  const chain = greedyChain(seed);
  // Only ship seeds that afford a decent target chain (so "par" is meaningful).
  if (chain.length < 5) continue;
  seenSeeds.add(seed);
  puzzles.push({
    id: `chain-${String(puzzles.length + 1).padStart(3, "0")}`,
    seed,
    par: chain.length - 1, // links beyond the seed
    // a sample long chain (for the "reveal a possible chain" nudge + headless check)
    sample: chain,
  });
}

for (const p of puzzles.slice(0, 10)) {
  console.log(`  ${p.seed}  par ${p.par}  [${p.sample.join(" → ")}]`);
}
console.log(`\n  built ${puzzles.length} puzzles.`);

const banner =
  "// AUTO-GENERATED by scripts/gen-chain.js — do not edit by hand.\n" +
  "// Daily Chain puzzles (seed word + a par-length target) for the cabinet at\n" +
  "// #/play/chain. Words are validated at runtime against the common-words dict.\n" +
  "// Run `npm run gen:chain` to regenerate.\n";

fs.mkdirSync(OUT_DIR, { recursive: true });
fs.writeFileSync(
  path.join(OUT_DIR, OUT_FILE),
  `${banner}export default ${JSON.stringify(puzzles, null, 2)};\n`
);

console.log(`\n✓ wrote ${puzzles.length} puzzles → src/data/generated/${OUT_FILE}\n`);
