/* ============================================================
   SNAPSHOT-LIVE — bakes the admin overlay (Firestore live/content)
   into src/data/generated/live.js.

   The #/admin console writes to Firestore, and every visitor merges
   that doc over the baked content pools at runtime (src/data/live.js).
   This script is the other half of that loop: it commits the overlay
   back into the repo so that

     1. the content renders on FIRST PAINT, before the Firestore read
        resolves (and still renders if Firestore is unreachable), and
     2. every edit made from a phone lands in git history like a normal
        content commit — and gets audited by `npm run check:daily`,
        which now sees admin-authored artifacts too.

   Firestore stays the authority: hydrateLive() replaces this seed on
   boot, and adds dedupe by id, so nothing ever shows up twice.

   SOFT-FAIL BY DESIGN (same as snapshot-archive.js): no service
   account, a failed read, or a missing doc leaves the committed file
   exactly as it is. Never clobber good data with an empty file.

   Run:  npm run snapshot:live   (needs FIREBASE_SERVICE_ACCOUNT)
   ============================================================ */

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { getDb } from "./lib/firebase-admin.js";
import { loadEnv } from "./lib/research.js";
import { LIVE_TYPES } from "../src/data/live.js";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const OUT = path.join(ROOT, "src", "data", "generated", "live.js");

loadEnv(ROOT);

// Keep only the three known operations, in a stable key order so the committed
// file diffs cleanly night to night. Firestore metadata (updatedAt) is dropped —
// a Timestamp doesn't belong in a bundled module.
function cleanLayer(raw) {
  const adds = Array.isArray(raw?.adds) ? raw.adds.filter((a) => a && typeof a === "object" && a.id) : [];
  const hides = Array.isArray(raw?.hides) ? raw.hides.filter((h) => typeof h === "string") : [];
  const patches = raw?.patches && typeof raw.patches === "object" ? raw.patches : {};

  const layer = {};
  if (adds.length) layer.adds = adds;
  if (Object.keys(patches).length) layer.patches = sortKeys(patches);
  if (hides.length) layer.hides = [...hides].sort();
  return Object.keys(layer).length ? layer : null;
}

function sortKeys(obj) {
  return Object.fromEntries(Object.keys(obj).sort().map((k) => [k, obj[k]]));
}

async function main() {
  console.log("Snapshotting the live content overlay…");

  const db = await getDb();
  if (!db) {
    console.warn("snapshot-live: no DB handle — leaving the existing snapshot in place.");
    return;
  }

  let data;
  try {
    const snap = await db.collection("live").doc("content").get();
    if (!snap.exists) {
      console.log("snapshot-live: live/content doesn't exist yet (console never used) — nothing to bake.");
      return;
    }
    data = snap.data();
  } catch (e) {
    console.warn(`snapshot-live: read failed (${e?.message || e}) — leaving the existing snapshot in place.`);
    return;
  }

  const out = {};
  const counts = [];
  for (const type of LIVE_TYPES) {
    const layer = cleanLayer(data?.[type]);
    if (!layer) continue;
    out[type] = layer;
    counts.push(
      `${type}:${layer.adds?.length || 0}+${Object.keys(layer.patches || {}).length}~${layer.hides?.length || 0}`
    );
  }

  fs.writeFileSync(
    OUT,
    `// AUTO-GENERATED by scripts/snapshot-live.js — do not edit by hand.\n` +
      `// Baked copy of the live overlay (Firestore live/content), so admin edits render\n` +
      `// on first paint instead of waiting on the network — and so they land in git.\n` +
      `// Shape: { <type>: { adds: [], patches: {}, hides: [] } }. See src/data/live.js.\n` +
      `export default ${JSON.stringify(out, null, 2)};\n`
  );

  console.log(
    `  wrote src/data/generated/live.js` +
      (counts.length ? ` (${counts.join(" ")} — adds+patches~hides)` : " (overlay is empty)")
  );
  console.log("\n✓ done");
}

main().catch((e) => {
  console.warn(`snapshot-live: unexpected error (${e?.message || e}) — leaving the existing snapshot in place.`);
});
