/* ============================================================
   SNAPSHOT-ARCHIVE — mirrors the permanent Firestore archive into
   committed static JSON the browser can read (the site never reads
   Firestore directly; firestore.rules keep archive/* admin-only).

   FINDS ONLY: we snapshot the three "discovery" types — stumble,
   weird, curiosities — the timeless, stumble-worthy internet finds.
   The "in-the-moment" types (polls/quizzes/buzz/countdowns/hotornot/
   news/tips/onthisday) belong to "today", not a back catalogue, so
   they stay in Firestore but are NOT snapshotted.

   Two outputs, mirroring animations.js's bundle-size split:
   - src/data/generated/vault.js        full corpus (lazy-imported)
   - src/data/generated/vault-index.js  tiny summary (eager-imported)

   Every find is normalized to the Stumble ARTIFACT shape so the app
   renders them all through one card:
     { id, kind, era, title, blurb, year?, url, source, archivedAt }
   - weird/curiosity items get a sensible kind/era default.
   - de-duped by urlKey across types (a find archived as both "weird"
     and "stumble" appears once).

   SOFT-FAIL BY DESIGN (same philosophy as the generators): if
   FIREBASE_SERVICE_ACCOUNT is missing or a read throws, or too few
   items come back, we log a warning and write NOTHING — the
   previously committed snapshot keeps serving. Never clobber good
   data with an empty file.

   Run:  npm run snapshot:archive   (needs FIREBASE_SERVICE_ACCOUNT)
   ============================================================ */

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { getDb } from "./lib/firebase-admin.js";
import { urlKey } from "./lib/validate-urls.js";
import { loadEnv } from "./lib/research.js";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const OUT_DIR = path.join(ROOT, "src", "data", "generated");

// Load FIREBASE_SERVICE_ACCOUNT from a local .env when present (CI passes it as a
// real env var; loadEnv only fills vars not already set, so it's safe in both).
loadEnv(ROOT);

// The discovery types we mirror, in display priority order. `source` is stamped
// onto each item so the Vault can show provenance without it driving the UI.
const TYPES = ["stumble", "weird", "curiosities"];

// weird/curiosity items have no `kind`/`era` of their own — give them a sensible
// default so the one shared ArtifactCard (keyed on kind) renders them. wiki-ish
// curiosities read as "wiki"; weird-web finds read as living "site"s.
const DEFAULT_KIND = { weird: "site", curiosities: "wiki", stumble: "site" };
const DEFAULT_ERA = { weird: "current", curiosities: "timeless", stumble: "timeless" };

// Firestore Timestamp → plain ISO string (portable + diffable in the committed file).
function toIso(runAt) {
  try {
    if (!runAt) return null;
    if (typeof runAt.toDate === "function") return runAt.toDate().toISOString();
    if (runAt._seconds != null) return new Date(runAt._seconds * 1000).toISOString();
  } catch {
    /* fall through */
  }
  return null;
}

// One archived doc → the artifact shape the app already renders.
function toArtifact(type, data) {
  const id = String(data.id || "").trim();
  const url = String(data.url || "").trim();
  const year = String(data.year || "").trim();
  return {
    id,
    kind: String(data.kind || DEFAULT_KIND[type] || "site").trim(),
    era: String(data.era || DEFAULT_ERA[type] || "timeless").trim(),
    title: String(data.title || "").trim(),
    blurb: String(data.blurb || "").trim(),
    ...(year ? { year } : {}),
    url,
    source: type,
    ...(toIso(data.runAt) ? { archivedAt: toIso(data.runAt) } : {}),
  };
}

async function readType(db, type) {
  const snap = await db.collection("archive").doc(type).collection("items").get();
  return snap.docs.map((d) => toArtifact(type, d.data()));
}

function writeModule(file, value, banner) {
  fs.writeFileSync(
    path.join(OUT_DIR, file),
    `// AUTO-GENERATED by scripts/snapshot-archive.js — do not edit by hand.\n` +
      `// ${banner}\n` +
      `export default ${JSON.stringify(value, null, 2)};\n`
  );
}

async function main() {
  console.log("Snapshotting the archive (finds only: stumble + weird + curiosities)…");

  const db = await getDb();
  if (!db) {
    // getDb already warned. Soft-fail: leave the committed snapshot untouched.
    console.warn("snapshot: no DB handle — leaving the existing snapshot in place.");
    return;
  }

  let raw;
  try {
    const batches = await Promise.all(TYPES.map((t) => readType(db, t)));
    raw = batches.flat();
  } catch (e) {
    console.warn(`snapshot: read failed (${e?.message || e}) — leaving the existing snapshot in place.`);
    return;
  }

  // Keep only well-formed finds, then de-dupe by URL (stumble wins over weird
  // wins over curiosities thanks to TYPES order + flat()).
  const perType = {};
  const seenUrls = new Set();
  const seenIds = new Set();
  const items = [];
  for (const a of raw) {
    if (!a.id || !a.title || !a.blurb || !a.url) continue;
    const key = urlKey(a.url);
    if (seenIds.has(a.id) || seenUrls.has(key)) continue;
    seenIds.add(a.id);
    seenUrls.add(key);
    items.push(a);
    perType[a.source] = (perType[a.source] || 0) + 1;
  }

  // Newest first by archivedAt (undated sink to the bottom — older manual seeds).
  items.sort((x, y) => String(y.archivedAt || "").localeCompare(String(x.archivedAt || "")));

  // Guard: an empty/near-empty result almost certainly means a transient read
  // problem, not "the archive is empty" — refuse to clobber a good snapshot.
  if (items.length < 1) {
    console.warn("snapshot: 0 valid items — refusing to overwrite. Leaving the existing snapshot in place.");
    return;
  }

  const newest = items[0]?.archivedAt || null;
  const index = { total: items.length, byType: perType, newest, builtAt: new Date().toISOString() };

  writeModule(
    "vault.js",
    items,
    "The Vault — every timeless internet find ever archived (stumble + weird + curiosities), normalized to the Stumble artifact shape. Lazy-imported (can be large)."
  );
  writeModule(
    "vault-index.js",
    index,
    "Vault summary for instant header render. Shape: { total, byType, newest, builtAt }. Eager-imported (tiny)."
  );

  console.log(
    `  wrote src/data/generated/vault.js (${items.length} finds — ` +
      Object.entries(perType).map(([t, n]) => `${t}:${n}`).join(" ") +
      `) + vault-index.js`
  );
  console.log("\n✓ done");
}

main().catch((e) => {
  // Last-resort guard: still soft-fail so a hiccup never breaks a content run.
  console.warn(`snapshot: unexpected error (${e?.message || e}) — leaving the existing snapshot in place.`);
});
